error handling

diff --git a/.github/workflows/notify-slack.yml b/.github/workflows/notify-slack.yml
--- a/.github/workflows/notify-slack.yml
+++ b/.github/workflows/notify-slack.yml
@@ -43,8 +43,12 @@ jobs:
             MESSAGE="Please review the changes: "
             for OWNER in "${OWNERS[@]}"; do
               MESSAGE+="@$OWNER "
-              echo @MESSAGE
-              echo @SLACK_WEBHOOK_URL
             done
-            curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"New Pull Request: *${PR_TITLE}* opened by ${PR_USER}\n${PR_URL}\"}" $SLACK_WEBHOOK_URL
+            response=$(curl -s -w "%{http_code}" -X POST -H 'Content-type: application/json' --data "{\"text\":\"New Pull Request: *${PR_TITLE}* opened by ${PR_USER}\n${PR_URL}\"}" $SLACK_WEBHOOK_URL)
+            body=$(echo $response | sed -e 's/[0-9]*$//')
+            status=$(echo $response | grep -o '[0-9]*$')
+            if [ "$status" -ne 200 ]; then
+              echo "Error sending message to Slack: $body"
+              exit 1
+            fi
           fi
